/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScBaseDate: typeof import('./components/ScBaseDate/index.vue')['default']
    ScButton: typeof import('./components/ScBaseComponents/ScButton/index.vue')['default']
    ScColumnItem: typeof import('./components/ScBaseComponents/ScTable/ScColumnItem.vue')['default']
    ScDate: typeof import('./components/ScBaseFormItems/ScDate/index.vue')['default']
    ScDatePicker: typeof import('./components/ScBaseFormItems/ScDatePicker/index.vue')['default']
    ScDateRangePicker: typeof import('./components/ScBaseFormItems/ScDateRangePicker/index.vue')['default']
    ScInput: typeof import('./components/ScBaseFormItems/ScInput/index.vue')['default']
    ScPageContent: typeof import('./components/ScBaseComponents/ScPageContent/index.vue')['default']
    ScSearchbar: typeof import('./components/ScBaseComponents/ScSearchbar/index.vue')['default']
    ScSelect: typeof import('./components/ScBaseFormItems/ScSelect/index.vue')['default']
    ScTable: typeof import('./components/ScBaseComponents/ScTable/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
  const ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScBaseDate: typeof import('./components/ScBaseDate/index.vue')['default']
  const ScButton: typeof import('./components/ScBaseComponents/ScButton/index.vue')['default']
  const ScColumnItem: typeof import('./components/ScBaseComponents/ScTable/ScColumnItem.vue')['default']
  const ScDate: typeof import('./components/ScBaseFormItems/ScDate/index.vue')['default']
  const ScDatePicker: typeof import('./components/ScBaseFormItems/ScDatePicker/index.vue')['default']
  const ScDateRangePicker: typeof import('./components/ScBaseFormItems/ScDateRangePicker/index.vue')['default']
  const ScInput: typeof import('./components/ScBaseFormItems/ScInput/index.vue')['default']
  const ScPageContent: typeof import('./components/ScBaseComponents/ScPageContent/index.vue')['default']
  const ScSearchbar: typeof import('./components/ScBaseComponents/ScSearchbar/index.vue')['default']
  const ScSelect: typeof import('./components/ScBaseFormItems/ScSelect/index.vue')['default']
  const ScTable: typeof import('./components/ScBaseComponents/ScTable/index.vue')['default']
  const SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
}